// data.js — generated by scripts/import-csv.js
// DO NOT edit by hand. Re-run the script to update from Notion CSV exports.
//
// Sources:
//    89 items  ←  LC Problems w Waves 30c55905e48b80bd84d5db7b753fc04a_all.csv
//    40 items  ←  System Design Topics 30c55905e48b80cfbd81f7fa3d4ae3f8_all.csv
// Total: 129 items
//
// To add a new source database:
//   1. Export from Notion as CSV into resources/notion_raw/
//   2. Add an entry to SOURCE_FILES in scripts/import-csv.js
//   3. Run: node scripts/import-csv.js

export default {
  "resources": [
    {
      "id": "lc-1-two-sum",
      "title": "Two Sum",
      "category": "DSA",
      "subcategory": "Array",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "array",
        "hash table",
        "wave 1"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Hash maps, pair search | Pattern: Hash Table | Wave 1"
    },
    {
      "id": "lc-121-best-time-to-buy-sell-stock",
      "title": "Best Time to Buy/Sell Stock",
      "category": "DSA",
      "subcategory": "Array",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "array",
        "single pass",
        "wave 1"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Tracking min/max | Pattern: Single Pass | Wave 1"
    },
    {
      "id": "lc-217-contains-duplicate",
      "title": "Contains Duplicate",
      "category": "DSA",
      "subcategory": "Array",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "array",
        "hash set",
        "wave 1"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Set operations | Pattern: Hash Set | Wave 1"
    },
    {
      "id": "lc-242-valid-anagram",
      "title": "Valid Anagram",
      "category": "DSA",
      "subcategory": "String",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "string",
        "hash table",
        "wave 1"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "String comparison | Pattern: Hash Table | Wave 1"
    },
    {
      "id": "lc-125-valid-palindrome",
      "title": "Valid Palindrome",
      "category": "DSA",
      "subcategory": "String",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "string",
        "two pointers",
        "wave 1"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "String validation | Pattern: Two Pointers | Wave 1"
    },
    {
      "id": "lc-3-longest-substring-without-repeating",
      "title": "Longest Substring Without Repeating",
      "category": "DSA",
      "subcategory": "String",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "string",
        "sliding window",
        "wave 1"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Window optimization | Pattern: Sliding Window | Wave 1"
    },
    {
      "id": "lc-424-longest-repeating-character-replacement",
      "title": "Longest Repeating Character Replacement",
      "category": "DSA",
      "subcategory": "String",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "string",
        "sliding window",
        "wave 1"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Character frequency | Pattern: Sliding Window | Wave 1"
    },
    {
      "id": "lc-49-group-anagrams",
      "title": "Group Anagrams",
      "category": "DSA",
      "subcategory": "String",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "string",
        "hash table",
        "wave 1"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "String categorization | Pattern: Hash Table | Wave 1"
    },
    {
      "id": "lc-560-subarray-sum-equals-k",
      "title": "Subarray Sum Equals K",
      "category": "DSA",
      "subcategory": "Prefix Sum",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "prefix sum",
        "hash map",
        "wave 1"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Cumulative sum + hash map | Pattern: Hash Map | Wave 1"
    },
    {
      "id": "lc-525-contiguous-array",
      "title": "Contiguous Array",
      "category": "DSA",
      "subcategory": "Prefix Sum",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "prefix sum",
        "hash map",
        "wave 1"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Balance count with hash map | Pattern: Hash Map | Wave 1"
    },
    {
      "id": "lc-930-binary-subarrays-with-sum",
      "title": "Binary Subarrays With Sum",
      "category": "DSA",
      "subcategory": "Prefix Sum",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "prefix sum",
        "hash map",
        "wave 1"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Target sum counting | Pattern: Hash Map | Wave 1"
    },
    {
      "id": "lc-238-product-of-array-except-self",
      "title": "Product of Array Except Self",
      "category": "DSA",
      "subcategory": "Array",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "array",
        "prefix/suffix",
        "wave 1"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Array manipulation | Pattern: Prefix/Suffix | Wave 1"
    },
    {
      "id": "lc-53-maximum-subarray",
      "title": "Maximum Subarray",
      "category": "DSA",
      "subcategory": "Array",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "array",
        "kadane's algorithm",
        "wave 1"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Running sum | Pattern: Kadane's Algorithm | Wave 1"
    },
    {
      "id": "lc-15-3sum",
      "title": "3Sum",
      "category": "DSA",
      "subcategory": "Array",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "array",
        "two pointers",
        "wave 1"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Sorted array traversal | Pattern: Two Pointers | Wave 1"
    },
    {
      "id": "lc-11-container-with-most-water",
      "title": "Container With Most Water",
      "category": "DSA",
      "subcategory": "Array",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "array",
        "two pointers",
        "wave 1"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Area calculation | Pattern: Two Pointers | Wave 1"
    },
    {
      "id": "lc-76-minimum-window-substring",
      "title": "Minimum Window Substring",
      "category": "DSA",
      "subcategory": "String",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "string",
        "sliding window",
        "wave 1"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Multi-character tracking | Pattern: Sliding Window | Wave 1"
    },
    {
      "id": "lc-206-reverse-linked-list",
      "title": "Reverse Linked List",
      "category": "DSA",
      "subcategory": "Linked List",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "linked list",
        "iterative/recursive",
        "wave 2"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Pointer manipulation | Pattern: Iterative/Recursive | Wave 2"
    },
    {
      "id": "lc-21-merge-two-sorted-lists",
      "title": "Merge Two Sorted Lists",
      "category": "DSA",
      "subcategory": "Linked List",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "linked list",
        "two pointers",
        "wave 2"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "List merging | Pattern: Two Pointers | Wave 2"
    },
    {
      "id": "lc-141-linked-list-cycle",
      "title": "Linked List Cycle",
      "category": "DSA",
      "subcategory": "Linked List",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "linked list",
        "fast & slow pointers",
        "wave 2"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Cycle detection | Pattern: Fast & Slow Pointers | Wave 2"
    },
    {
      "id": "lc-19-remove-nth-node-from-end",
      "title": "Remove Nth Node From End",
      "category": "DSA",
      "subcategory": "Linked List",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "linked list",
        "two pointers",
        "wave 2"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "List traversal | Pattern: Two Pointers | Wave 2"
    },
    {
      "id": "lc-143-reorder-list",
      "title": "Reorder List",
      "category": "DSA",
      "subcategory": "Linked List",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "linked list",
        "multiple patterns",
        "wave 2"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Find middle + reverse + merge | Pattern: Multiple Patterns | Wave 2"
    },
    {
      "id": "lc-146-lru-cache",
      "title": "LRU Cache",
      "category": "DSA",
      "subcategory": "Linked List",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "linked list",
        "design (hash + dll)",
        "wave 2"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Cache implementation | Pattern: Design (Hash + DLL) | Wave 2"
    },
    {
      "id": "lc-155-min-stack",
      "title": "Min Stack",
      "category": "DSA",
      "subcategory": "Stack",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "stack",
        "design",
        "wave 2"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "O(1) min retrieval | Pattern: Design | Wave 2"
    },
    {
      "id": "lc-739-daily-temperatures",
      "title": "Daily Temperatures",
      "category": "DSA",
      "subcategory": "Stack",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "stack",
        "monotonic stack",
        "wave 2"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Next greater element | Pattern: Monotonic Stack | Wave 2"
    },
    {
      "id": "lc-84-largest-rectangle-in-histogram",
      "title": "Largest Rectangle in Histogram",
      "category": "DSA",
      "subcategory": "Stack",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "stack",
        "monotonic stack",
        "wave 2"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Area calculation | Pattern: Monotonic Stack | Wave 2"
    },
    {
      "id": "lc-42-trapping-rain-water",
      "title": "Trapping Rain Water",
      "category": "DSA",
      "subcategory": "Stack",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "stack",
        "monotonic stack",
        "wave 2"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Water between bars | Pattern: Monotonic Stack | Wave 2"
    },
    {
      "id": "lc-239-sliding-window-maximum",
      "title": "Sliding Window Maximum",
      "category": "DSA",
      "subcategory": "Queue",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "queue",
        "monotonic deque",
        "wave 2"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Max in sliding window | Pattern: Monotonic Deque | Wave 2"
    },
    {
      "id": "lc-226-invert-binary-tree",
      "title": "Invert Binary Tree",
      "category": "DSA",
      "subcategory": "Binary Tree",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "binary tree",
        "dfs",
        "wave 3"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Tree traversal | Pattern: DFS | Wave 3"
    },
    {
      "id": "lc-104-maximum-depth-of-binary-tree",
      "title": "Maximum Depth of Binary Tree",
      "category": "DSA",
      "subcategory": "Binary Tree",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "binary tree",
        "dfs/bfs",
        "wave 3"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Recursion | Pattern: DFS/BFS | Wave 3"
    },
    {
      "id": "lc-100-same-tree",
      "title": "Same Tree",
      "category": "DSA",
      "subcategory": "Binary Tree",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "binary tree",
        "dfs",
        "wave 3"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Tree comparison | Pattern: DFS | Wave 3"
    },
    {
      "id": "lc-572-subtree-of-another-tree",
      "title": "Subtree of Another Tree",
      "category": "DSA",
      "subcategory": "Binary Tree",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "binary tree",
        "dfs",
        "wave 3"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Pattern matching | Pattern: DFS | Wave 3"
    },
    {
      "id": "lc-102-binary-tree-level-order-traversal",
      "title": "Binary Tree Level Order Traversal",
      "category": "DSA",
      "subcategory": "Binary Tree",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "binary tree",
        "bfs",
        "wave 3"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Queue-based traversal | Pattern: BFS | Wave 3"
    },
    {
      "id": "lc-98-validate-binary-search-tree",
      "title": "Validate Binary Search Tree",
      "category": "DSA",
      "subcategory": "BST",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "bst",
        "dfs + range",
        "wave 3"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "BST validation | Pattern: DFS + Range | Wave 3"
    },
    {
      "id": "lc-230-kth-smallest-element-in-bst",
      "title": "Kth Smallest Element in BST",
      "category": "DSA",
      "subcategory": "BST",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "bst",
        "in-order traversal",
        "wave 3"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "BST ordering | Pattern: In-order Traversal | Wave 3"
    },
    {
      "id": "lc-105-construct-tree-from-preorder-inorder",
      "title": "Construct Tree from Preorder/Inorder",
      "category": "DSA",
      "subcategory": "Binary Tree",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "binary tree",
        "divide & conquer",
        "wave 3"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Tree reconstruction | Pattern: Divide & Conquer | Wave 3"
    },
    {
      "id": "lc-124-binary-tree-maximum-path-sum",
      "title": "Binary Tree Maximum Path Sum",
      "category": "DSA",
      "subcategory": "Binary Tree",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "binary tree",
        "dfs + global max",
        "wave 3"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Path optimization | Pattern: DFS + Global Max | Wave 3"
    },
    {
      "id": "lc-297-serialize-deserialize-binary-tree",
      "title": "Serialize/Deserialize Binary Tree",
      "category": "DSA",
      "subcategory": "Binary Tree",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "binary tree",
        "bfs/dfs",
        "wave 3"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Tree encoding | Pattern: BFS/DFS | Wave 3"
    },
    {
      "id": "lc-133-clone-graph",
      "title": "Clone Graph",
      "category": "DSA",
      "subcategory": "Graph Traversal",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "graph traversal",
        "dfs/bfs",
        "wave 4"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Graph copying | Pattern: DFS/BFS | Wave 4"
    },
    {
      "id": "lc-200-number-of-islands",
      "title": "Number of Islands",
      "category": "DSA",
      "subcategory": "Graph Traversal",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "graph traversal",
        "dfs/bfs",
        "wave 4"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Connected components | Pattern: DFS/BFS | Wave 4"
    },
    {
      "id": "lc-417-pacific-atlantic-water-flow",
      "title": "Pacific Atlantic Water Flow",
      "category": "DSA",
      "subcategory": "Graph Traversal",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "graph traversal",
        "multi-source bfs/dfs",
        "wave 4"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Multi-source search | Pattern: Multi-source BFS/DFS | Wave 4"
    },
    {
      "id": "lc-207-course-schedule",
      "title": "Course Schedule",
      "category": "DSA",
      "subcategory": "Topological Sort",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "topological sort",
        "cycle detection",
        "wave 4"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "DFS/Kahn's algorithm | Pattern: Cycle Detection | Wave 4"
    },
    {
      "id": "lc-210-course-schedule-ii",
      "title": "Course Schedule II",
      "category": "DSA",
      "subcategory": "Topological Sort",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "topological sort",
        "ordering",
        "wave 4"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Order determination | Pattern: Ordering | Wave 4"
    },
    {
      "id": "lc-684-redundant-connection",
      "title": "Redundant Connection",
      "category": "DSA",
      "subcategory": "Union Find",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "union find",
        "cycle detection",
        "wave 4"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Find redundant edge | Pattern: Cycle Detection | Wave 4"
    },
    {
      "id": "lc-721-accounts-merge",
      "title": "Accounts Merge",
      "category": "DSA",
      "subcategory": "Union Find",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "union find",
        "grouping",
        "wave 4"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Merge by email | Pattern: Grouping | Wave 4"
    },
    {
      "id": "lc-127-word-ladder",
      "title": "Word Ladder",
      "category": "DSA",
      "subcategory": "Graph Traversal",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "graph traversal",
        "bfs",
        "wave 4"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Shortest path | Pattern: BFS | Wave 4"
    },
    {
      "id": "lc-269-alien-dictionary",
      "title": "Alien Dictionary",
      "category": "DSA",
      "subcategory": "Topological Sort",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "topological sort",
        "graph construction",
        "wave 4"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Build graph + topo sort | Pattern: Graph Construction | Wave 4"
    },
    {
      "id": "lc-685-redundant-connection-ii",
      "title": "Redundant Connection II",
      "category": "DSA",
      "subcategory": "Union Find",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 4,
      "weakAreaTags": [
        "union find",
        "cycle detection",
        "wave 4"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Directed graph cycle | Pattern: Cycle Detection | Wave 4"
    },
    {
      "id": "lc-215-kth-largest-element-in-array",
      "title": "Kth Largest Element in Array",
      "category": "DSA",
      "subcategory": "Heap",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "heap",
        "min heap",
        "wave 5"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Quick select / heap | Pattern: Min Heap | Wave 5"
    },
    {
      "id": "lc-347-top-k-frequent-elements",
      "title": "Top K Frequent Elements",
      "category": "DSA",
      "subcategory": "Heap",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "heap",
        "frequency count",
        "wave 5"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Heap / bucket sort | Pattern: Frequency Count | Wave 5"
    },
    {
      "id": "lc-373-find-k-pairs-with-smallest-sums",
      "title": "Find K Pairs with Smallest Sums",
      "category": "DSA",
      "subcategory": "K-way Merge",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "k-way merge",
        "heap selection",
        "wave 5"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Pair selection | Pattern: Heap Selection | Wave 5"
    },
    {
      "id": "lc-378-kth-smallest-element-in-sorted-matrix",
      "title": "Kth Smallest Element in Sorted Matrix",
      "category": "DSA",
      "subcategory": "K-way Merge",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "k-way merge",
        "matrix traversal",
        "wave 5"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Matrix with heap | Pattern: Matrix Traversal | Wave 5"
    },
    {
      "id": "lc-23-merge-k-sorted-lists",
      "title": "Merge K Sorted Lists",
      "category": "DSA",
      "subcategory": "K-way Merge",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "k-way merge",
        "heap merge",
        "wave 5"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Multi-way merge with heap | Pattern: Heap Merge | Wave 5"
    },
    {
      "id": "lc-295-find-median-from-data-stream",
      "title": "Find Median from Data Stream",
      "category": "DSA",
      "subcategory": "Heap",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "heap",
        "two heaps",
        "wave 5"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Max heap + min heap | Pattern: Two Heaps | Wave 5"
    },
    {
      "id": "lc-480-sliding-window-median",
      "title": "Sliding Window Median",
      "category": "DSA",
      "subcategory": "Heap",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "heap",
        "two heaps",
        "wave 5"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Dynamic median | Pattern: Two Heaps | Wave 5"
    },
    {
      "id": "lc-502-ipo",
      "title": "IPO",
      "category": "DSA",
      "subcategory": "Heap",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "heap",
        "two heaps",
        "wave 5"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Greedy + two heaps | Pattern: Two Heaps | Wave 5"
    },
    {
      "id": "lc-56-merge-intervals",
      "title": "Merge Intervals",
      "category": "DSA",
      "subcategory": "Intervals",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "intervals",
        "merging",
        "wave 5"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Overlap detection | Pattern: Merging | Wave 5"
    },
    {
      "id": "lc-57-insert-interval",
      "title": "Insert Interval",
      "category": "DSA",
      "subcategory": "Intervals",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "intervals",
        "merging",
        "wave 5"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Insert and merge | Pattern: Merging | Wave 5"
    },
    {
      "id": "lc-435-non-overlapping-intervals",
      "title": "Non-overlapping Intervals",
      "category": "DSA",
      "subcategory": "Intervals",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "intervals",
        "greedy selection",
        "wave 5"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Maximum non-overlapping | Pattern: Greedy Selection | Wave 5"
    },
    {
      "id": "lc-986-interval-list-intersections",
      "title": "Interval List Intersections",
      "category": "DSA",
      "subcategory": "Intervals",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "intervals",
        "two pointers",
        "wave 5"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Find intersections | Pattern: Two Pointers | Wave 5"
    },
    {
      "id": "lc-253-meeting-rooms-ii",
      "title": "Meeting Rooms II",
      "category": "DSA",
      "subcategory": "Intervals",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "intervals",
        "min heap",
        "wave 5"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Min rooms needed | Pattern: Min Heap | Wave 5"
    },
    {
      "id": "lc-70-climbing-stairs",
      "title": "Climbing Stairs",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "1d dp",
        "wave 6"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Fibonacci pattern | Pattern: 1D DP | Wave 6"
    },
    {
      "id": "lc-198-house-robber",
      "title": "House Robber",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "1d dp",
        "wave 6"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Sequential optimization | Pattern: 1D DP | Wave 6"
    },
    {
      "id": "lc-213-house-robber-ii",
      "title": "House Robber II",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "1d dp",
        "wave 6"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Circular array | Pattern: 1D DP | Wave 6"
    },
    {
      "id": "lc-322-coin-change",
      "title": "Coin Change",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "unbounded knapsack",
        "wave 6"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Minimum coins | Pattern: Unbounded Knapsack | Wave 6"
    },
    {
      "id": "lc-518-coin-change-ii",
      "title": "Coin Change II",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "unbounded knapsack",
        "wave 6"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Combination count | Pattern: Unbounded Knapsack | Wave 6"
    },
    {
      "id": "lc-300-longest-increasing-subsequence",
      "title": "Longest Increasing Subsequence",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "1d dp",
        "wave 6"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Subsequence tracking | Pattern: 1D DP | Wave 6"
    },
    {
      "id": "lc-139-word-break",
      "title": "Word Break",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "1d dp",
        "wave 6"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Dictionary lookup | Pattern: 1D DP | Wave 6"
    },
    {
      "id": "lc-91-decode-ways",
      "title": "Decode Ways",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "1d dp",
        "wave 6"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "String decoding | Pattern: 1D DP | Wave 6"
    },
    {
      "id": "lc-62-unique-paths",
      "title": "Unique Paths",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "2d dp",
        "wave 6"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Grid traversal | Pattern: 2D DP | Wave 6"
    },
    {
      "id": "lc-152-maximum-product-subarray",
      "title": "Maximum Product Subarray",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "1d dp",
        "wave 6"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Product tracking | Pattern: 1D DP | Wave 6"
    },
    {
      "id": "lc-416-partition-equal-subset-sum",
      "title": "Partition Equal Subset Sum",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "0/1 knapsack",
        "wave 6"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Subset selection | Pattern: 0/1 Knapsack | Wave 6"
    },
    {
      "id": "lc-1143-longest-common-subsequence",
      "title": "Longest Common Subsequence",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "2d dp",
        "wave 6"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "String matching | Pattern: 2D DP | Wave 6"
    },
    {
      "id": "lc-72-edit-distance",
      "title": "Edit Distance",
      "category": "DSA",
      "subcategory": "Dynamic Programming",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "dynamic programming",
        "2d dp",
        "wave 6"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "String transformation | Pattern: 2D DP | Wave 6"
    },
    {
      "id": "lc-78-subsets",
      "title": "Subsets",
      "category": "DSA",
      "subcategory": "Backtracking",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "backtracking",
        "combinations",
        "wave 7"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Subset generation | Pattern: Combinations | Wave 7"
    },
    {
      "id": "lc-39-combination-sum",
      "title": "Combination Sum",
      "category": "DSA",
      "subcategory": "Backtracking",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "backtracking",
        "combinations",
        "wave 7"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Target sum | Pattern: Combinations | Wave 7"
    },
    {
      "id": "lc-40-combination-sum-ii",
      "title": "Combination Sum II",
      "category": "DSA",
      "subcategory": "Backtracking",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "backtracking",
        "combinations",
        "wave 7"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Target with duplicates | Pattern: Combinations | Wave 7"
    },
    {
      "id": "lc-46-permutations",
      "title": "Permutations",
      "category": "DSA",
      "subcategory": "Backtracking",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "backtracking",
        "permutations",
        "wave 7"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Order matters | Pattern: Permutations | Wave 7"
    },
    {
      "id": "lc-47-permutations-ii",
      "title": "Permutations II",
      "category": "DSA",
      "subcategory": "Backtracking",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "backtracking",
        "permutations",
        "wave 7"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "With duplicates | Pattern: Permutations | Wave 7"
    },
    {
      "id": "lc-79-word-search",
      "title": "Word Search",
      "category": "DSA",
      "subcategory": "Backtracking",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "backtracking",
        "grid search",
        "wave 7"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "2D DFS | Pattern: Grid Search | Wave 7"
    },
    {
      "id": "lc-131-palindrome-partitioning",
      "title": "Palindrome Partitioning",
      "category": "DSA",
      "subcategory": "Backtracking",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "backtracking",
        "string partition",
        "wave 7"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Palindrome splits | Pattern: String Partition | Wave 7"
    },
    {
      "id": "lc-22-generate-parentheses",
      "title": "Generate Parentheses",
      "category": "DSA",
      "subcategory": "Backtracking",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "backtracking",
        "constraint building",
        "wave 7"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Valid combinations | Pattern: Constraint Building | Wave 7"
    },
    {
      "id": "lc-212-word-search-ii",
      "title": "Word Search II",
      "category": "DSA",
      "subcategory": "Trie",
      "difficulty": "Hard",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "trie",
        "backtracking",
        "wave 7"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Board + Trie | Pattern: Backtracking | Wave 7"
    },
    {
      "id": "lc-704-binary-search",
      "title": "Binary Search",
      "category": "DSA",
      "subcategory": "Binary Search",
      "difficulty": "Easy",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "binary search",
        "basic template",
        "wave 8"
      ],
      "estimatedMinutes": 45,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Classic binary search | Pattern: Basic Template | Wave 8"
    },
    {
      "id": "lc-33-search-in-rotated-sorted-array",
      "title": "Search in Rotated Sorted Array",
      "category": "DSA",
      "subcategory": "Binary Search",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "binary search",
        "modified search",
        "wave 8"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Pivot finding | Pattern: Modified Search | Wave 8"
    },
    {
      "id": "lc-153-find-minimum-in-rotated-sorted-array",
      "title": "Find Minimum in Rotated Sorted Array",
      "category": "DSA",
      "subcategory": "Binary Search",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "binary search",
        "modified search",
        "wave 8"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Find minimum | Pattern: Modified Search | Wave 8"
    },
    {
      "id": "lc-74-search-a-2d-matrix",
      "title": "Search a 2D Matrix",
      "category": "DSA",
      "subcategory": "Binary Search",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "binary search",
        "2d search",
        "wave 8"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Matrix flattening | Pattern: 2D Search | Wave 8"
    },
    {
      "id": "lc-875-koko-eating-bananas",
      "title": "Koko Eating Bananas",
      "category": "DSA",
      "subcategory": "Binary Search",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "binary search",
        "search on answer",
        "wave 8"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Optimization problem | Pattern: Search on Answer | Wave 8"
    },
    {
      "id": "lc-1011-capacity-to-ship-packages",
      "title": "Capacity To Ship Packages",
      "category": "DSA",
      "subcategory": "Binary Search",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "binary search",
        "search on answer",
        "wave 8"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Capacity optimization | Pattern: Search on Answer | Wave 8"
    },
    {
      "id": "lc-981-time-based-key-value-store",
      "title": "Time Based Key-Value Store",
      "category": "DSA",
      "subcategory": "Binary Search",
      "difficulty": "Medium",
      "sourceDatabase": "LC Problems w/ Waves",
      "status": "parked",
      "priority": 2,
      "weakAreaTags": [
        "binary search",
        "design",
        "wave 8"
      ],
      "estimatedMinutes": 60,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Timestamp search | Pattern: Design | Wave 8"
    },
    {
      "id": "sd-design-a-real-time-presence-system",
      "title": "Design a Real-Time Presence System",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-design-a-rate-limiter",
      "title": "Design a Rate Limiter",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-design-an-e-commerce-backend-cart-inventory-orders",
      "title": "Design an E-Commerce Backend (Cart, Inventory, Orders)",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-design-an-analytics-event-ingestion-pipeline",
      "title": "Design an Analytics / Event Ingestion Pipeline",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-design-a-search-autocomplete-service",
      "title": "Design a Search Autocomplete Service",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-design-a-distributed-cache-service",
      "title": "Design a Distributed Cache Service",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-design-a-notification-and-alerts-system",
      "title": "Design a Notification and Alerts System",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-design-a-youtube-style-streaming-platform",
      "title": "Design a YouTube-Style Streaming Platform",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-design-a-whatsapp-style-chat-system",
      "title": "Design a WhatsApp-Style Chat System",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-design-an-instagram-style-photo-sharing-system",
      "title": "Design an Instagram-Style Photo Sharing System",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-design-a-twitter-style-feed",
      "title": "Design a Twitter-Style Feed",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-design-a-url-shortener",
      "title": "Design a URL Shortener",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    },
    {
      "id": "sd-designing-for-data-locality",
      "title": "Designing for Data Locality",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "distributed systems",
        "concept",
        "designing for data locality"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 6 - Designing for Data Locality | Concept"
    },
    {
      "id": "sd-hotspot-and-data-skew-mitigation",
      "title": "Hotspot and Data Skew Mitigation",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "distributed systems",
        "concept",
        "performance / traffic"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 3 - Performance / Traffic | Concept"
    },
    {
      "id": "sd-scheduling-and-background-job-processing",
      "title": "Scheduling and Background Job Processing",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "distributed systems",
        "architecture",
        "async & event-driven systems"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 5 - Async & Event-Driven Systems | Architecture"
    },
    {
      "id": "sd-service-discovery-and-configuration-management",
      "title": "Service Discovery and Configuration Management",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "distributed systems",
        "architecture",
        "async & event-driven systems"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 5 - Async & Event-Driven Systems | Architecture"
    },
    {
      "id": "sd-distributed-transactions-and-sagas-high-level",
      "title": "Distributed Transactions and Sagas (High-Level)",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "distributed systems",
        "concept",
        "distributed systems"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 4 - Distributed Systems | Concept"
    },
    {
      "id": "sd-idempotency-and-delivery-semantics",
      "title": "Idempotency and Delivery Semantics",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "distributed systems",
        "concept",
        "distributed systems"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 4 - Distributed Systems | Concept"
    },
    {
      "id": "sd-event-driven-architecture-basics",
      "title": "Event-Driven Architecture Basics",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "distributed systems",
        "concept",
        "async & event-driven systems"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 5 - Async & Event-Driven Systems | Concept"
    },
    {
      "id": "sd-message-queues-and-pub-sub-systems",
      "title": "Message Queues and Pub/Sub Systems",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "distributed systems",
        "concept",
        "async & event-driven systems"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 5 - Async & Event-Driven Systems | Concept"
    },
    {
      "id": "sd-distributed-systems-failure-modes-and-recovery",
      "title": "Distributed Systems Failure Modes and Recovery",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "distributed systems",
        "concept",
        "distributed systems"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 4 - Distributed Systems | Concept"
    },
    {
      "id": "sd-reliability-patterns-retries-circuit-breakers-bulkheads",
      "title": "Reliability Patterns (Retries, Circuit Breakers, Bulkheads)",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "distributed systems",
        "architecture",
        "distributed systems"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 4 - Distributed Systems | Architecture"
    },
    {
      "id": "sd-cap-pacelc-in-real-systems",
      "title": "CAP & PACELC in Real Systems",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "distributed systems",
        "concept",
        "distributed systems"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 4 - Distributed Systems | Concept"
    },
    {
      "id": "sd-consistency-models-strong-eventual-causal",
      "title": "Consistency Models (Strong, Eventual, Causal)",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "distributed systems",
        "concept",
        "distributed systems"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 4 - Distributed Systems | Concept"
    },
    {
      "id": "sd-sharding-and-partitioning-strategies",
      "title": "Sharding and Partitioning Strategies",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "distributed systems",
        "concept",
        "data & storage"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 2 - Data & Storage | Concept"
    },
    {
      "id": "sd-replication-strategies-sync-vs-async",
      "title": "Replication Strategies (Sync vs Async)",
      "category": "System Design",
      "subcategory": "Distributed systems",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "distributed systems",
        "concept",
        "data & storage"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 2 - Data & Storage | Concept"
    },
    {
      "id": "sd-system-design-interview-framework-and-trade-off-communication",
      "title": "System Design Interview Framework and Trade-Off Communication",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "fundamentals",
        "mock interview",
        "core thinking"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 1 - Core Thinking | Mock Interview"
    },
    {
      "id": "sd-security-and-authentication-at-scale-tokens-gateways",
      "title": "Security and Authentication at Scale (Tokens, Gateways)",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "fundamentals",
        "concept",
        "architecture shape"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 7 - Architecture Shape | Concept"
    },
    {
      "id": "sd-monolith-vs-microservices-architectures",
      "title": "Monolith vs Microservices Architectures",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "fundamentals",
        "architecture",
        "architecture shape"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 7 - Architecture Shape | Architecture"
    },
    {
      "id": "sd-back-of-the-envelope-estimation-in-system-design",
      "title": "Back-of-the-Envelope Estimation in System Design",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "fundamentals",
        "mock interview",
        "core thinking"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 1 - Core Thinking | Mock Interview"
    },
    {
      "id": "sd-rate-limiting-and-throttling-strategies",
      "title": "Rate Limiting and Throttling Strategies",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "fundamentals",
        "concept",
        "performance / traffic"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 3 - Performance / Traffic | Concept"
    },
    {
      "id": "sd-observability-logging-metrics-and-monitoring",
      "title": "Observability: Logging, Metrics, and Monitoring",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "fundamentals",
        "concept",
        "designing for data locality"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 6 - Designing for Data Locality | Concept"
    },
    {
      "id": "sd-load-balancing-fundamentals",
      "title": "Load Balancing Fundamentals",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "fundamentals",
        "concept",
        "performance / traffic"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 3 - Performance / Traffic | Concept"
    },
    {
      "id": "sd-cache-invalidation-strategies",
      "title": "Cache Invalidation Strategies",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "fundamentals",
        "concept",
        "performance / traffic"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 3 - Performance / Traffic | Concept"
    },
    {
      "id": "sd-caching-fundamentals-and-patterns",
      "title": "Caching Fundamentals and Patterns",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "fundamentals",
        "concept",
        "performance / traffic"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 3 - Performance / Traffic | Concept"
    },
    {
      "id": "sd-sql-vs-nosql-databases-in-system-design",
      "title": "SQL vs NoSQL Databases in System Design",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "fundamentals",
        "concept",
        "data & storage"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 2 - Data & Storage | Concept"
    },
    {
      "id": "sd-data-modeling-for-scalable-systems",
      "title": "Data Modeling for Scalable Systems",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "fundamentals",
        "concept",
        "data & storage"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 2 - Data & Storage | Concept"
    },
    {
      "id": "sd-api-design-for-large-scale-systems",
      "title": "API Design for Large-Scale Systems",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "fundamentals",
        "concept",
        "core thinking"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 1 - Core Thinking | Concept"
    },
    {
      "id": "sd-core-system-qualities-scalability-reliability-availability-performance",
      "title": "Core System Qualities: Scalability, Reliability, Availability, Performance",
      "category": "System Design",
      "subcategory": "Fundamentals",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 5,
      "weakAreaTags": [
        "fundamentals",
        "concept",
        "core thinking"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 1 - Core Thinking | Concept"
    },
    {
      "id": "sd-design-a-metrics-aggregation-system",
      "title": "Design a Metrics Aggregation System",
      "category": "System Design",
      "subcategory": "Case Study",
      "difficulty": "Medium",
      "sourceDatabase": "System Design Topics",
      "status": "parked",
      "priority": 3,
      "weakAreaTags": [
        "case study",
        "architecture",
        "case studies"
      ],
      "estimatedMinutes": 90,
      "lastTouchedAt": null,
      "confidence": 3,
      "notes": "Phase 8 - Case Studies | Architecture"
    }
  ],
  "weeklyPlan": {
    "weekOf": "",
    "targetDSA": 4,
    "targetSystemDesign": 2,
    "targetDBInternals": 0,
    "plannedHours": 7,
    "actualHours": 0,
    "selectedItemIds": [],
    "retrospective": "",
    "nextWeekFocus": ""
  },
  "sessions": [],
  "reflections": []
};
